### ISSUE TITLE
Convert each dataset to their respective entities

### ISSUE THREAD

**Issue by adesca** [invinst/invisible-flow#11]
This is a spike to write the code for converting from foia data to the invisible institute schema  datatypes

Refer to definitions for the schema and sample datasets

**Comment by tw-jeff-burroughs** [comment]
Example of all foia responses received so far: https://www.dropbox.com/sh/ofbjm1yc493zrpe/AAA2wQzhoOBNXVY7900YtT8Ta/frozen?dl=0&lst=&subfolder_nav_tracking=1

**Comment by tw-jeff-burroughs** [comment]
completion looks like conversion code that can be used for issue 12 (creating and saving entity files for use in db upload #13)
