### ISSUE TITLE
Scraping COPA data

### ISSUE THREAD

**Issue by adesca** [invinst/invisible-flow#15]
AS Sarah 
I WANT TO download Copa data
AND store it in an s3 bucket under Scrape-[timestamp]\initial_data
WITH a JSON metadata file that contains: 
- git: url for the repository at the commit where this code game from
- Source: SCRAPER/copa

**Comment by tw-jeff-burroughs** [comment]
@adesca Do you know how we go about getting the git commit information for the metadata file on this ticket?  I have it all done but that one part.

**Comment by tw-jeff-burroughs** [comment]
complete with commit 1ce3f7d3e5146b6d000a6f08dd9ac9cc557c98d3
