### ISSUE TITLE
BUG: log_no missing from Allegation

### ISSUE THREAD

**Issue by adesca** [invinst/invisible-flow#48]
Add log_no to allegation after transforming from case_info

**Comment by tw-jeff-burroughs** [comment]
Added data_allegation table's cr_id added from original data LOG_NO column

<img width="836" alt="Screen Shot 2019-08-07 at 2 36 33 PM" src="https://user-images.githubusercontent.com/50185149/62659673-dd09a680-b920-11e9-9cd8-434f775cce41.png">
