### ISSUE TITLE
Specifying foia response type

### ISSUE THREAD

**Issue by adesca** [invinst/invisible-flow#6]
AS Alex
I WANT TO be able to specify what data from the FOIA response that I'm uploading
SO THAT the correct processing is done on it

Further elaboration on the specific types of foia response data are in the definition for 060 foia response in the Definitions card

**Comment by tw-jeff-burroughs** [comment]
blocked by #3

**Comment by terrencebunkley** [comment]
https://github.com/invinst/invisible-flow/pull/31
